export interface PropertyProps {
  address: string;
  availableFrom?: string;
  charger: boolean;
  city: string;
  conditioner: boolean;
  createdAt: { seconds: number; nanoseconds: number };
  culteries: boolean;
  customQuestion?: string;
  deposit?: number;
  elevator: boolean;
  favorite: string;
  firstQuestion?: string;
  floorArea: number;
  furnishing: string;
  gym: boolean;
  hotWater: boolean;
  id: string;
  images: string[];
  microwave: boolean;
  monthlyRent: number;
  numberBathrooms: number;
  numberBedrooms: number;
  ownerId: string;
  parking: boolean;
  playground: boolean;
  pool: boolean;
  propertyType: string;
  secondQuestion: string;
  status: string;
  title: string;
  tv: boolean;
  userId: string;
  verified: boolean;
  views: number;
  washingMachine: boolean;
}
