export interface PropertyProps {
  address: string;
  city: string;
  availableFrom?: string;
  deposit?: number;
  floorArea: number;
  propertyType: string;
  monthlyRent: number;
  title: string;
  images: string[];
  numberBedrooms: number;
  numberBathrooms: number;
  createdAt: { seconds: number; nanoseconds: number };
  views: number;
  favorite: string;
  active: boolean;
  id: string;
  userId: string;
  furnishing: string;
  customQuestion?: string;
  status: string;
  ownerId: string;
  gym: boolean;
  pool: boolean;
  parking: boolean;
  playground: boolean;
  elevator: boolean;
  charger: boolean;
  hotWater: boolean;
  microwave: boolean;
  washingMachine: boolean;
  tv: boolean;
  conditioner: boolean;
  culteries: boolean;
}
