export interface PropertyProps {
  address: string;
  place: string;
  availableFrom?: string;
  deposit?: number;
  floorArea: number;
  propertyType: string;
  monthlyRent: number;
  title: string;
  image1?: string;
  image2?: string;
  image3?: string;
  image4?: string;
  image5?: string;
  image6?: string;
  image7?: string;
  image8?: string;
  image9?: string;
  numberBedrooms: number;
  numberBathrooms: number;
  createdAt: { seconds: number; nanoseconds: number };
  views: number;
  favorite: string;
  active: boolean;
  id: string;
  userId: string;
  furnishing: string;
  customQuestion?: string;
  status: string;
  ownerId: string;
}
